"""add price and remove created_at from order

Revision ID: d247a0c757a1
Revises: 47e7d83e37be
Create Date: 2026-07-23 21:07:04.135447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd247a0c757a1'
down_revision: Union[str, Sequence[str], None] = '47e7d83e37be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('price', sa.Float(), nullable=True))
    op.drop_column('orders', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('created_at', sa.DATETIME(), nullable=True))
    op.drop_column('orders', 'price')
    # ### end Alembic commands ###
